build: add python 3.12 support
eduNEXT/tutor-contrib-codejail pull request #52
Opened 2024-04-30 22:24 UTC by MaferMazu

## Description
This PR:
- Add Python 3.12 to our CI checks.
- Remove pkg_resources based on https://github.com/overhangio/cookiecutter-tutor-plugin/commit/5d5241d198e57dd72cf254727bb5e7f8c3780f87
- Update requirements

2024-05-01 00:23 UTC, MoisesGSalas requested changes
You will also need to update the minimum version of tutor required to 17.0.2 https://github.com/eduNEXT/tutor-contrib-codejail/blob/4406c7c835e8509dcb9a084b7fa98d597183ef5b/setup.py#L47

`importlib-metadata` and `importlib-resources` were added in https://github.com/overhangio/tutor/commit/d99b2feeb30fa772dca48345c8992b4eafdeac21 which was first included in the 17.0.2 release.

2024-05-02 21:52 UTC, MaferMazu commented
Nice catch. Thanks, @MoisesGSalas. Do you have other feedback, or are we okay?

2024-05-02 21:53 UTC, MoisesGSalas approved these changes

2024-05-03 22:48 UTC, merged

2024-05-03 22:53 UTC, MaferMazu commented
I won't create a release for this change since we will soon create a release for Redwood. See #50.

If you need a release before Redwood, please open an issue.